DROP TABLE IF EXISTS qr_code;

CREATE TABLE qr_code (
  id BIGSERIAL PRIMARY KEY,
  uniq_code VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  path VARCHAR(255) NOT NULL UNIQUE
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO barcode_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO barcode_admin;